language: bash
services: docker

env:
  - PHP_IMAGE_TAG=5.6-fpm PHALCON_VERSION=2.0.10
  - PHP_IMAGE_TAG=7.1-fpm PHALCON_VERSION=3.1.2

before_script:
  - IMAGE="braska/php-fpm-phalcon"

script:
  - docker build -t "$IMAGE:$PHP_IMAGE_TAG-$PHALCON_VERSION" .
  - docker images
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  - docker push $IMAGE
